version: '1.0'
stages:
  - clone
  - test
  - pakcages
  - release
steps:
  main_clone:
    title: 'Cloning main repository...'
    stage: clone
    type: git-clone
    repo: "${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}"
    revision: "${{CF_REVISION}}"
    git: cf_github

  go_fmt:
    title: 'Formatting'
    stage: test
    image:  goreleaser/goreleaser:v1.11.3
    commands:
      - go fmt
  
  go_test:
    title: 'Run tests'
    stage: test
    image:  goreleaser/goreleaser:v1.11.3
    environment:
      - TF_ACC="test"
    commands:
      - go test -v ./... 
    retry:
      maxAttempts: 3
      delay: 5
      exponentialFactor: 2

  prepare_env_vars:
    title: 'Preparing environment variables...'
    stage: release
    image: codefreshio/ci-helpers
    environment:
      - GPG_FINGERPRINT=${{GPG_FINGERPRINT}}
      - SIGNINGKEY=${{SIGNINGKEY}}
    commands:
      - source /get-token/get-gh-token.sh
      - cf_export GITHUB_TOKEN
      - cf_export GPG_FINGERPRINT
      - cf_export SIGNINGKEY
      - cf_export GPG_PRIVATE
    when:
      condition:
        all:
          release: "'${{RELEASE}}' == 'true'"

  release_binaries:
    title: Create release in Github
    image:  goreleaser/goreleaser:v1.6.3
    stage: release
    environment:
      - GPG_FINGERPRINT=${{GPG_FINGERPRINT}}
      - SIGNINGKEY=${{SIGNINGKEY}}
      - GPG_PRIVATE=${{GPG_PRIVATE}}
    commands:
      - apk update
      - apk fetch gnupg
      - apk add gnupg
      - echo ${GPG_PRIVATE} | base64 -d > /tmp/private.key
      - gpg --import /tmp/private.key
      - git config user.signingkey ${GPG_FINGERPRINT}
      - git clean -fdx
      - goreleaser release --rm-dist
    when:
      condition:
        all:
          release: "'${{RELEASE}}' == 'true'"
