version: "1.0"
stages:
  - clone
  - test
  - release
steps:
  main_clone:
    title: "Cloning main repository..."
    stage: clone
    type: git-clone
    repo: "${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}"
    revision: "${{CF_REVISION}}"
    git: cf_github

  go_fmt:
    title: "Formatting"
    stage: test
    image: goreleaser/goreleaser:v1.17.0
    commands:
      - go fmt

  go_test:
    title: "Run tests"
    stage: test
    image: golang:1.23-alpine3.21
    environment:
      - TF_ACC="test"
      - CGO_ENABLED=0
    commands:
      - go install github.com/warrensbox/terraform-switcher@0.13.1308
      - terraform-switcher --latest-stable ${TF_VERSION}
      - sleep $((RANDOM % 45))
      - go test -v ./...
    retry:
      maxAttempts: 3
      delay: 5
      exponentialFactor: 2
    matrix:
      # The following will resolve to their latest patch version
      environment:
        - TF_VERSION=1.3.0
        - TF_VERSION=1.7.0
    when:
      condition:
        all:
          release: "'${{RELEASE}}' != 'true'"

  prepare_env_vars:
    title: "Preparing environment variables..."
    stage: release
    image: quay.io/codefresh/codefresh-shell:0.0.13
    shell: bash
    environment:
      - GPG_FINGERPRINT=${{GPG_FINGERPRINT}}
      - SIGNINGKEY=${{SIGNINGKEY}}
    commands:
      - source /scripts/get-gh-token.sh
      - cf_export GITHUB_TOKEN=$GITHUB_TOKEN --mask
      - cf_export GPG_FINGERPRINT
      - cf_export SIGNINGKEY
      - cf_export GPG_PRIVATE
    when:
      condition:
        all:
          release: "'${{RELEASE}}' == 'true'"

  release_binaries:
    title: Create release in Github
    image: goreleaser/goreleaser:v1.17.0
    stage: release
    environment:
      - GPG_FINGERPRINT=${{GPG_FINGERPRINT}}
      - SIGNINGKEY=${{SIGNINGKEY}}
      - GPG_PRIVATE=${{GPG_PRIVATE}}
    commands:
      - apk update
      - apk fetch gnupg
      - apk add gnupg
      - echo ${GPG_PRIVATE} | base64 -d > /tmp/private.key
      - gpg --import /tmp/private.key
      - git config user.signingkey ${GPG_FINGERPRINT}
      - git clean -fdx
      - goreleaser release --rm-dist
    when:
      condition:
        all:
          release: "'${{RELEASE}}' == 'true'"
